TpAnualWeb/TpAnualWeb/Controllers/CriteriosCategoriasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TP_Anual.Egresos;
using TP_Anual.DAOs;

namespace TpAnualWeb.Controllers
{
    public class CriteriosCategoriasController : Controller
    {
        // GET: CriterioCategoria
        public ActionResult CriteriosCategorias()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CargarCriterio(string descripcion = "", int jerarquia = -1)
        {
            if (descripcion == "" || jerarquia == -1)
            {
                ViewBag.mostrar = "ERROR";
                ViewBag.error = "Debe completar todos los campos";

                return View("Mostrar");
            }
            else
            {
                var nuevo = new Criterio();
                nuevo.descripcion = descripcion;
                nuevo.jerarquia = jerarquia;

                CriterioCategoriaDAO.getInstancia().AddCriterio(nuevo);

                ViewBag.mostrar = "SUCCESS";
                ViewBag.success = "Se cargo el criterio " + nuevo.descripcion + " correctamente!";

                return View("Mostrar");

            }

        }

        [HttpPost]
        public ActionResult CargarCategoriaAcriterio(string descripcionCat = "", string descripcionCrit = "")
        {
            if (descripcionCat == "" || descripcionCrit == "")
            {
                ViewBag.mostrar = "ERROR";
                ViewBag.error = "Debe completar todos los campos";

                return View("Mostrar");
            }
            else
            {
                var critero = CriterioCategoriaDAO.getInstancia().getCriterioByDescripcion(descripcionCrit);

                if (critero == null)
                {
                    ViewBag.mostrar = "ERROR";
                    ViewBag.error = "No existe el criterio ingresado";

                    return View("Mostrar");
                }
                else
                {
                    var nuevo = new Categoria();
                    nuevo.descripcion = descripcionCat;

                    var criterio = CriterioCategoriaDAO.getInstancia().getCriterioByDescripcion(descripcionCrit);
                    nuevo.criterio = criterio;

                    CriterioCategoriaDAO.getInstancia().AddCategoria(nuevo);

                    ViewBag.mostrar = "SUCCESS";
                    ViewBag.success = "Se agrego la categoria " + nuevo.descripcion + " al criterio " + criterio.descripcion + "!";

                    return View("Mostrar");
                }
            }
        }

        [HttpPost]
        public ActionResult AsignarCategoria(string item_desc = "", string categoria = "")
        {

            if (item_desc == "" || categoria == "")
            {
                ViewBag.mostrar = "ERROR";
                ViewBag.error = "Debe completar todos los campos";

                return View("Mostrar");
            }
            else
            {
                var item = ItemDAO.getInstancia().getItemByDescripcion(item_desc);
                var cat = CriterioCategoriaDAO.getInstancia().getCategoriaByDescripcion(categoria);
                var cri = CriterioCategoriaDAO.getInstancia().getCriterioByID(cat.id_criterio);

                if (item == null || cat == null)
                {
                    ViewBag.mostrar = "ERROR";
                    ViewBag.error = "Los datos ingresados no son validos";

                    return View("Mostrar");

                }
                else
                {

                    ItemDAO.getInstancia().AgregarCriterioItem(item, cat, cri);

                    ViewBag.mostrar = "SUCCESS";
                    ViewBag.success = ($"Se ha asociado la categoria {cat.descripcion} al item {item.descripcion}");

                    return View("Mostrar");

                }
            }
        }


    }
}

TpAnualWeb/TpAnualWeb/Controllers/IngresoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TP_Anual.DAOs;
using TP_Anual.Egresos;

namespace TpAnualWeb.Controllers
{
    public class IngresoController : Controller
    {
        // GET: Ingreso
        public ActionResult Ingreso()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CargarIngreso(string descripcion = "", int total = -1)
        {
            if (total == -1 || descripcion == "")
            {
                ViewBag.mostrar = "ERROR";
                ViewBag.error = "Debe completar todos los campos";

                return View("Mostrar");
            }
            else
            {
                if (total < 0)
                {
                    ViewBag.mostrar = "ERROR";
                    ViewBag.error = "El total debe ser mayor que 0";

                    return View("Mostrar");
                }
                else
                {
                    Ingreso nuevo = new Ingreso(descripcion, total);
                    var ingreso = IngresoDAO.getInstancia().Add(nuevo);

                    ViewBag.mostrar = "SUCCESS";
                    ViewBag.success = ($"Se creo el ingreso {ingreso.descripcion} de id: {ingreso.id_ingreso} correctamente!");

                    return View("Mostrar");
                }
            }
        }


        [HttpPost]
        public ActionResult FechaPrimerEgreso(string id_egresos, string id_ingresos)
        {

            var egresos = id_egresos.Split('-');
            var ingresos = id_ingresos.Split('-');

            if (IngresoDAO.getInstancia().asociarFechaPrimerEgreso(egresos, ingresos))
            {
                ViewBag.mostrar = "SUCCESS";
                ViewBag.success = ($"Se realizo la asociacion correctamente!");

                return View("Mostrar");
            }
            else
            {
                ViewBag.mostrar = "ERROR";
                ViewBag.error = "Los datos ingresados no son validos";

                return View("Mostrar");
            }
        }

        [HttpPost]
        public ActionResult ValorPrimerEgreso(string id_egresos, string id_ingresos)
        {
            var egresos = id_egresos.Split('-');
            var ingresos = id_ingresos.Split('-');

            if (IngresoDAO.getInstancia().asociarValorPrimerEgreso(egresos, ingresos))
            {
                ViewBag.mostrar = "SUCCESS";
                ViewBag.success = ($"Se realizo la asociacion correctamente!");

                return View("Mostrar");
            }
            else
            {
                ViewBag.mostrar = "ERROR";
                ViewBag.error = "Los datos ingresados no son validos";

                return View("Mostrar");
            }

        }

        [HttpPost]
        public ActionResult ValorPrimerIngreso(string id_egresos, string id_ingresos)
        {
            var egresos = id_egresos.Split('-');
            var ingresos = id_ingresos.Split('-');

            if (IngresoDAO.getInstancia().asociarValorPrimerIngreso(egresos, ingresos))
            {
                ViewBag.mostrar = "SUCCESS";
                ViewBag.success = ($"Se realizo la asociacion correctamente!");

                return View("Mostrar");
            }
            else
            {
                ViewBag.mostrar = "ERROR";
                ViewBag.error = "Los datos ingresados no son validos";

                return View("Mostrar");
            }
        }


    }
}

TpAnualWeb/TpAnualWeb/Controllers/ProveedoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TP_Anual.DAOs;
using TP_Anual.Egresos;

namespace TpAnualWeb.Controllers
{
    public class ProveedoresController : Controller
    {
        // GET: Proveedor
        public ActionResult Proveedores()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CargarProveedor(string razon = "", string CUIT = "")
        {
            if (razon == "" || CUIT == "")
            {
                ViewBag.mostrar = "ERROR";
                ViewBag.error = "Debe completar todos los campos";

                return View("Mostrar");
            }
            else
            {
                Proveedor nuevo = new Proveedor();
                nuevo.CUIT = CUIT;
                nuevo.razon_social = razon;
                ProveedorDAO.getInstancia().Add(nuevo);

                ViewBag.mostrar = "SUCCESS";
                ViewBag.success = "Se cargo el proveedor correctamente!";

                return View("Mostrar");
            }

        }

    }
}

TpAnualWeb/TpAnualWeb/Controllers/ProyectoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TP_Anual.DAOs;
using TP_Anual.Administrador_Inicio_Sesion;
using TP_Anual.Egresos;


namespace TpAnualWeb.Controllers
{
    public class ProyectoController : Controller
    {
        // GET: Proyecto
        public ActionResult Proyecto()
        {
            return View();
        }


        [HttpPost]
        public ActionResult CargarProyecto(int monto = -1, int cant_presupuestos = -1, string usuario = "")
        {
            if (monto == -1 || cant_presupuestos == -1 || usuario == "")
            {
                ViewBag.mostrar = "ERROR";
                ViewBag.error = "Debe completar todos los campos";

                return View("Mostrar");
            }
            else
            {
                if (UsuarioDAO.getInstancia().getUsuarioByUserName(usuario) == null || monto < 0)
                {
                    ViewBag.mostrar = "ERROR";
                    ViewBag.error = "Los datos ingresados no son validos";

                    return View("Mostrar");
                }
                else
                {
                    var proyecto = ProyectoDAO.getInstancia().cargarProyecto(cant_presupuestos, monto, usuario);

                    ViewBag.mostrar = "SUCCESS";
                    ViewBag.success = ($"Se creo el proyecto de id: {proyecto.id} correctamente!");

                    return View("Mostrar");

                }
            }

        }

        [HttpPost]
        public ActionResult VincularIngresoConProyecto(int id_ingreso = -1, int id_proyecto = -1)
        {
            if (id_ingreso == -1 || id_proyecto == -1)
            {
                ViewBag.mostrar = "ERROR";
                ViewBag.error = "Debe completar todos los campos";

                return View("Mostrar");
            }
            else
            {
                var ingreso = IngresoDAO.getInstancia().getIngresoById(id_ingreso);
                var proyecto = ProyectoDAO.getInstancia().getProyectoById(id_proyecto);

                if (ingreso == null || proyecto == null)
                {
                    ViewBag.mostrar = "ERROR";
                    ViewBag.error = "Los datos ingresados no son validos";

                    return View("Mostrar");
                }
                else
                {
                    ProyectoDAO.getInstancia().vincularIngresoConProyecto(id_proyecto, id_ingreso);

                    ViewBag.mostrar = "SUCCESS";
                    ViewBag.success = ($"Se vinculo el ingreso {ingreso.descripcion} con el proyecto de id: {proyecto.id} correctamente!");

                    return View("Mostrar");

                }

            }

        }

        [HttpPost]
        public ActionResult VincularEgresoConProyecto(int id_egreso = -1, int id_proyecto = -1)
        {
            if (id_egreso == -1 || id_proyecto == -1)
            {
                ViewBag.mostrar = "ERROR";
                ViewBag.error = "Debe completar todos los campos";

                return View("Mostrar");
            }
            else
            {
                var egreso = EgresoDAO.getInstancia().getEgresoById(id_egreso);
                var proyecto = ProyectoDAO.getInstancia().getProyectoById(id_proyecto);

                if (egreso == null || proyecto == null)
                {
                    ViewBag.mostrar = "ERROR";
                    ViewBag.error = "Los datos ingresados no son validos";

                    return View("Mostrar");
                }
                else
                {
                    ProyectoDAO.getInstancia().vincularEgresoConProyecto(id_proyecto, id_egreso);

                    ViewBag.mostrar = "SUCCESS";
                    ViewBag.success = ($"Se vinculo el egreso {egreso.descripcion} con el proyecto de id: {proyecto.id} correctamente!");

                    return View("Mostrar");
                }
            }
        }

        [HttpPost]
        public ActionResult BajaProyecto(int id_proyecto = -1)
        {

            if (id_proyecto == -1)
            {
                ViewBag.mostrar = "ERROR";
                ViewBag.error = "Debe ingresar un proyecto";

                return View("Mostrar");
            }
            else
            {
                var proyecto = ProyectoDAO.getInstancia().getProyectoById(id_proyecto);

                if (proyecto == null)
                {
                    ViewBag.mostrar = "ERROR";
                    ViewBag.error = "No existe el proyecto ingresado";

                    return View("Mostrar");
                }
                else
                {
                    ProyectoDAO.getInstancia().bajaProyecto(id_proyecto);

                    ViewBag.mostrar = "SUCCESS";
                    ViewBag.success = ($"Se elimino el proyecto de id: {proyecto.id} correctamente!");

                    return View("Mostrar");
                }
            }
        }

    }
}

TpAnualWeb/TpAnualWeb/Views/Shared/CriteriosCategorias.cshtml
@{
    ViewBag.Title = "CriteriosCategorias";
}



<!DOCTYPE html>
<html lang="en">
<meta name="viewport" content="width=device-width" />
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>TP ANUAL DDS 2020 GRUPO 5</title>

    <!-- Bootstrap core CSS -->
    <link href="~/Content/boostrap/bootstrap.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="~/Content/scrolling-nav.css" rel="stylesheet">

</head>

<!-- Bootstrap core JavaScript -->
<script src="~/Scripts/vendor/jquery/jquery.min.js"></script>
<script src="~/Scripts/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- Plugin JavaScript -->
<script src="~/Scripts/vendor/jquery-easing/jquery.easing.min.js"></script>

<!-- Custom JavaScript for this theme -->
<script src="~/Scripts/scrolling-nav.js"></script>


<script src="~/Scripts/ajax.js"></script>


<body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
        <div class="container">
            <a href="@Url.Action("Index", "Home")" class="navbar-brand js-scroll-trigger" href="#page-top">GeSoc</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a href="@Url.Action("Index", "Home")#about" class="nav-link js-scroll-trigger">EGRESOS</a>
                    </li>
                    <li class="nav-item">
                            <a href="@Url.Action("Index", "Home")#services" class="nav-link js-scroll-trigger">INGRESOS</a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("Index", "Home")#proyectos" class="nav-link js-scroll-trigger">PROYECTOS</a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("Index", "Home")#proveedores" class="nav-link js-scroll-trigger">PROVEEDORES</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Home")#criterios_y_categorias" class="nav-link js-scroll-trigger">CRITERIOS Y CATEGORIAS</a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("Index", "Home")#bitacora_de_operaciones" class="nav-link js-scroll-trigger">BITACORA</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="@Url.Action("Index", "Home")#contact">GitHub</a>
                    </li>
                    <li class="nav-item">
                        <a onclick="myFunction(0)" class="nav-link js-scroll-trigger">@Session["UserName"]</a>
                    </li>
                    <li id="0">
                        <a href="@Url.Action("Login", "Home")" class="nav-link js-scroll-trigger" style="display:block; color:firebrick">Cerrar sesion</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <section id="criterios_y_categorias" class="bg-light">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">

                    <h2>CRITERIOS Y CATEGORIAS</h2>

                    <button onclick="myFunction(1)" target="_blank" class="button button2">Cargar criterio</button>
                    <div id="1" style="display:none;">

                        @using (Html.BeginForm("CargarCriterio", "CriterioCategoria", FormMethod.Post))
                        {
                            <p><input type="text" name="descripcion" placeholder="Descripcion" class="button button3"></p>
                            <p><input type="number" name="jerarquia" placeholder="Jerarquia" class="button button3"></p>

                            <p><input type="submit" value="Cargar criterio" class="button button4"></p>
                        }
                    </div>
                    <h6></h6>

                    <button onclick="myFunction(2)" target="_blank" class="button button2">Cargar categoria a criterio</button>
                    <div id="2" style="display:none;">

                        @using (Html.BeginForm("CargarCategoriaAcriterio", "CriterioCategoria", FormMethod.Post))
                        {
                            <p><input type="text" name="descripcionCat" placeholder="Descripcion categoria" class="button button3"></p>
                            <p><input type="text" name="descripcionCrit" placeholder="Descripcion criterio" class="button button3"></p>
                            <p><input type="submit" value="Cargar categoria" class="button button4"></p>
                        }
                    </div>
                    <h6></h6>

                    <button onclick="myFunction(3)" target="_blank" class="button button2">Asociar categoria a item</button>
                    <div id="3" style="display:none;">

                        @using (Html.BeginForm("AsignarCategoria", "CriterioCategoria", FormMethod.Post))
                        {
                            <p><input type="text" name="categoria" placeholder="Descripcion categoria" class="button button3"></p>
                            <p><input type="text" name="item_desc" placeholder="Descripcion item" class="button button3"></p>
                            <p><input type="submit" value="Asociar" class="button button4"></p>
                        }
                    </div>
                    <h6></h6>


                </div>
            </div>
        </div>
    </section>
</body>

TpAnualWeb/TpAnualWeb/Views/Shared/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<!DOCTYPE html>
<html>
<body>
    <!---------------------------------EGRESOS--------------------------------->
    <header class="bg-primary text-white">
        <div class="container text-center">
            <h1>GeSoc</h1>
            <p class="lead">Gestion de Proyectos Sociales</p>
        </div>
    </header>

    <section id="egresos">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h2>EGRESOS</h2>

                    <p class="lead">Seleccione una opcion:</p>
                    @Html.ActionLink("Cargar y validar", "Egreso", "Egreso", null, new { @class = "button button2" })
                    <p></p>

                    <button onclick="myFunction(1)" target="_blank" class="button button2">Buscar egresos</button>
                    <div id="1" style="display:none;">

                        <h6></h6>
                        @using (Html.BeginForm("MostrarEgresos", "Home", FormMethod.Post))
                        {
                            <input style="margin-left:40px;" type="submit" value="Mostrar todos los egresos" class="button button4">
                        }
                        <p></p>
                        <p style="margin-left:40px;">Buscar egreso por id:</p>
                        @using (Html.BeginForm("BuscarEgreso", "Home", FormMethod.Post))
                        {
                            <input style="margin-left:40px;" type="text" name="id_egreso" placeholder="ID del egreso" class="button button3" />
                            <input style="margin-left:40px;" type="submit" value="Buscar" class="button button4">
                        }
                        <p></p>


                    </div>
                    <p></p>

                    <button onclick="myFunction(2)" target="_blank" class="button button2">Buscar presupuestos</button>
                    <div id="2" style="display:none;">

                        <h6></h6>
                        @using (Html.BeginForm("MostrarPresupuestos", "Home", FormMethod.Post))
                        {
                            <input style="margin-left:40px;" type="submit" value="Mostrar todos los presupuestos" class="button button4">
                        }
                        <p></p>

                    </div>

                </div>
            </div>
        </div>
    </section>

    <!---------------------------------INGRESOS--------------------------------->

    <section id="ingresos" class="bg-light">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">

                    <h2>INGRESOS</h2>
                    <p class="lead">Seleccione una opcion:</p>

                    @Html.ActionLink("Cargar y asociar", "Ingreso", "Ingreso", null, new { @class = "button button2" })
                    <p></p>

                    <button onclick="myFunction(10)" target="_blank" class="button button2">Buscar Ingresos</button>
                    <div id="10" style="display:none;">

                        <h6></h6>
                        @using (Html.BeginForm("MostrarIngresos", "Home", FormMethod.Post))
                        {
                            <input style="margin-left:40px;" type="submit" value="Mostrar todos los ingresos" class="button button4">
                        }
                        <p style="margin-left:40px;">Buscar ingreso por id:</p>
                        @using (Html.BeginForm("BuscarIngreso", "Home", FormMethod.Post))
                        {
                            <input style="margin-left:40px;" type="text" name="id_ingreso" placeholder="ID del ingreso" class="button button3" />
                            <input style="margin-left:40px;" type="submit" value="Buscar" class="button button4">
                        }
                        <p></p>

                    </div>

                </div>
            </div>
        </div>
    </section>

    <!---------------------------------PROYECTOS--------------------------------->

    <section id="proyectos">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">

                    <h2>PROYECTOS</h2>
                    <p class="lead">Seleccione una opcion:</p>

                    @Html.ActionLink("Cargar y vincular", "Proyecto", "Proyecto", null, new { @class = "button button2" })
                    <p></p>

                    <button onclick="myFunction(30)" target="_blank" class="button button2">Buscar Proyectos</button>
                    <div id="30" style="display:none;">

                        <h4></h4>
                        @using (Html.BeginForm("MostrarProyectos", "Home", FormMethod.Post))
                        {
                            <input style="margin-left:40px;" type="submit" value="Mostrar todos los proyectos" class="button button4">
                        }
                        <p style="margin-left:40px;">Buscar proyecto por id:</p>
                        @using (Html.BeginForm("BuscarProyecto", "Home", FormMethod.Post))
                        {
                            <input style="margin-left:40px;" type="number" name="id_proyecto" placeholder="ID del Proyecto" class="button button3" />
                            <input style="margin-left:40px;" type="submit" value="Buscar" class="button button4">
                        }
                        <p></p>

                    </div>

                </div>
            </div>
        </div>
    </section>

    <!---------------------------------PROVEEDORES--------------------------------->

    <section id="proveedores" class="bg-light">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">

                    <h2>PROVEEDORES</h2>
                    <p class="lead">Seleccione una opcion:</p>

                    @Html.ActionLink("Registrar", "Proveedores", "Proveedores", null, new { @class = "button button2" })
                    <p></p>

                    @using (Html.BeginForm("MostrarProveedores", "Home", FormMethod.Post))
                    {
                        <input type="submit" value="Mostrar todos los proveedores" class="button button2">
                    }

                </div>
            </div>
        </div>
    </section>


    <!---------------------------------CRITERIOS Y CATEGORIAS--------------------------------->
    <section id="criterios_y_categorias">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">

                    <h2>CRITERIOS Y CATEGORIAS</h2>
                    <p class="lead">Seleccione una opcion:</p>

                    @Html.ActionLink("Cargar y asociar", "CriteriosCategorias", "CriteriosCategorias", null, new { @class = "button button2" })
                    <p></p>

                    <p></p>
                    @using (Html.BeginForm("MostrarCategorias", "Home", FormMethod.Post))
                    {
                        <input type="submit" value="Mostrar todas las categorias" class="button button2">
                    }

                    <p></p>
                    @using (Html.BeginForm("MostrarCriterios", "Home", FormMethod.Post))
                    {
                        <input type="submit" value="Mostrar todos los criterios" class="button button2">
                    }






                </div>
            </div>
        </div>
    </section>

    <!---------------------------------BITACORA DE OPERACIONES--------------------------------->
    <section id="bitacora_de_operaciones" class="bg-light">
        <div class="container">
            <div class="row">

                <div class="col-lg-8 mx-auto">
                    <h2>BITACORA DE OPERACIONES</h2>
                    @using (Html.BeginForm("verBitacora", "Home", FormMethod.Post))
                    {
                        <button target="_blank" class="button button2">Ver bitacora de operaciones</button>
                    }

                </div>
                <h6></h6>

            </div>
        </div>
    </section>

    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h2>Repositorio GitHub</h2>
                    <!-- <p class="lead"></p> -->
                    <a href="https://github.com/manupawlow/DDS-Grupo-5" target="_blank">Repositorio Grupo 5</a>
                </div>
            </div>
        </div>
    </section>

</body>
</html>